local ls = require "luasnip"
local r = ls.restore_node
local d = ls.dynamic_node
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local sn = ls.snippet_node
local rep = require("luasnip.extras").rep

ls.add_snippets("cpp", {

    s("mo", {
        t {
			"ll curL = 0, curR = -1",
            "for (auto& [l, r, index] : query) {",
            "    while (curR < r) add(++curR);",
            "    while (curR > r) remove(curR--);",
            "",
            "    while (curL < l) remove(curL++);",
            "    while (curL > l) add(--curL);",
            "    output[index] = ans;",
            "}",
        },
        i(0),
    }),

    s("lca_weighted_cpp", {
        t {
            "ll n, m;",
            "cin >> n >> m;",
            "umap<ll, vector<tuple<ll, ll>>> adj;",
            "loop(_, m) {",
            "    ll a, b, w;",
            "    cin >> a >> b >> w;",
            "    a--;",
            "    b--;",
            "    adj[a].push_back({b, w});",
            "    adj[b].push_back({a, w});",
            "}",
            "",
            "vll toin(n);",
            "vll toout(n);",
            "ll timer = 0;",
            "ll LOG = ceil(log2(n)) + 1;",
            "vector<vector<ll>> up(n, vector<ll>(LOG, -1));",
            "vector<vector<ll>> mx(n, vector<ll>(LOG, LLONG_MAX));",
            "",
            "function<void(ll, ll, ll)> dfs = [&](ll c, ll p, ll w) {",
            "    up[c][0] = p;",
            "    mx[c][0] = w;",
            "    toin[c] = ++timer;",
            "    for (int i = 1; i < LOG; i++) {",
            "        if (up[c][i - 1] != -1) {",
            "            up[c][i] = up[up[c][i - 1]][i - 1];",
            "            mx[c][i] = min(mx[up[c][i - 1]][i - 1], mx[c][i - 1]);",
            "        }",
            "    }",
            "    for (auto& [x, nw] : adj[c]) {",
            "        if (x != p) dfs(x, c, nw);",
            "    }",
            "    toout[c] = ++timer;",
            "};",
            "ll root = 0;",
            "dfs(root, -1, 0);",
            "",
            "function<bool(ll, ll)> isAncestor = [&](ll u, ll v) {",
            "    return (toin[u] < toin[v] && toout[u] > toout[v]);",
            "};",
            "",
            "function<ll(ll, ll)> get_min = [&](ll u, ll anc) {",
            "    ll res = LLONG_MAX;",
            "",
            "    for (int i = LOG - 1; i >= 0; --i) {",
            "        if (up[u][i] != -1 && !isAncestor(up[u][i], anc)) {",
            "            res = min(res, mx[u][i]);",
            "            u = up[u][i];",
            "        }",
            "    }",
            "",
            "    return res;",
            "};",
            "",
            "function<ll(ll, ll)> lca = [&](ll u, ll v) {",
            "    if (isAncestor(u, v)) return u;",
            "    if (isAncestor(v, u)) return v;",
            "",
            "    for (int i = LOG - 1; i >= 0; --i) {",
            "        if (up[u][i] != -1 && !isAncestor(up[u][i], v)) u = up[u][i];",
            "    }",
            "",
            "    return up[u][0];",
            "};",
            "",
            "ll q;",
            "cin >> q;",
            "loop(_, q) {",
            "    ll a, b;",
            "    cin >> a >> b;",
            "    a--;",
            "    b--;",
            "",
            "    ll L = lca(a, b);",
            "    ll mx_edge = min(get_min(a, L), get_min(b, L));",
            "    print(mx_edge);",
            "}",
        },
        i(0),
    }),

    s("kmp_cpp", {
        t {
            "# ---------- KMP String Matching (C++) ----------",
            "int kmp(string haystack, string needle) {",
            "    if (needle.size() == 0) return 0;",
            "    int n = haystack.size();",
            "    int m = needle.size();",
            "",
            "    int prev = 0, curr = 1;",
            "    vector<int> lps(m, 0);",
            "",
            "    while (curr < m) {",
            "        if (needle[curr] == needle[prev]) {",
            "            lps[curr] = prev + 1;",
            "            curr++;",
            "            prev++;",
            "        } else if (prev == 0) {",
            "            lps[curr] = 0;",
            "            curr++;",
            "        } else {",
            "            prev = lps[prev - 1];",
            "        }",
            "    }",
            "",
            "    int i = 0, j = 0;",
            "    while (i < n) {",
            "        if (haystack[i] == needle[j]) {",
            "            i++;",
            "            j++;",
            "        } else if (j == 0) {",
            "            i++;",
            "        } else {",
            "            j = lps[j - 1];",
            "        }",
            "",
            "        if (j == m) return i - m;",
            "    }",
            "",
            "    return -1;",
            "}",
        },
        i(0),
    }),

    s("merge_sort", {
        t {
            "vector<int> merge_array(const vector<int>& left, const vector<int>& right) {",
            "    vector<int> ans;",
            "    ans.reserve(left.size() + right.size());",
            "",
            "    int i = 0, j = 0;",
            "    while (i < left.size() && j < right.size()) {",
            "        if (left[i] < right[j]) {",
            "            ans.push_back(left[i++]);",
            "        } else {",
            "            ans.push_back(right[j++]);",
            "        }",
            "    }",
            "",
            "    while (i < (int)left.size()) ans.push_back(left[i++]);",
            "    while (j < (int)right.size()) ans.push_back(right[j++]);",
            "",
            "    return ans;",
            "}",
            "",
            "vector<int> merge_sort(const vector<int>& arr, int l, int r) {",
            "    if (l == r) return {arr[l]};",
            "",
            "    int mid = (l + r) / 2;",
            "    vector<int> left = merge_sort(arr, l, mid);",
            "    vector<int> right = merge_sort(arr, mid + 1, r);",
            "",
            "    return merge_array(left, right);",
            "}",
        },
    }),

    s("two_sat", {
        t {
            "class Two_SAT {",
            "        ll n;",
            "        ll vers;",
            "        vll n_vertices;",
            "        vll stack;",
            "        vll comp;",
            "        vector<bool> visited;",
            "        umap<ll, vll> adj;",
            "        umap<ll, vll> radj;",
            "",
            "        void dfs1(ll curr) {",
            "            visited[curr] = true;",
            "            for (ll x : adj[curr]) {",
            "                if (!visited[x]) dfs1(x);",
            "            }",
            "            stack.push_back(curr);",
            "        }",
            "",
            "        void dfs2(ll curr, ll id) {",
            "            comp[curr] = id;",
            "            for (ll x : radj[curr]) {",
            "                if (comp[x] == -1) dfs2(x, id);",
            "            }",
            "        }",
            "",
            "    public:",
            "        vector<bool> ass;",
            "        Two_SAT(ll n)",
            "            : n(n),",
            "              vers(2 * n) {",
            "            visited.assign(vers, false);",
            "            n_vertices.assign(n, false);",
            "            ass.assign(n, false);",
            "        }",
            "",
            "        bool solver() {",
            "            for (int i = 0; i < vers; i++) {",
            "                if (!visited[i]) dfs1(i);",
            "            }",
            "",
            "            comp.assign(vers, -1);",
            "            ll id = 0;",
            "",
            "            while (!stack.empty()) {",
            "                ll curr = stack.back();",
            "                stack.pop_back();",
            "                if (comp[curr] == -1) dfs2(curr, id++);",
            "            }",
            "",
            "            for (int i = 0; i < vers; i += 2) {",
            "                if (comp[i] == comp[i + 1]) return false;",
            "                ass[i / 2] = comp[i] > comp[i + 1];",
            "            }",
            "",
            "            return true;",
            "        }",
            "",
            "        void add_comp(ll a, bool na, ll b, bool nb) {",
            "            a = 2 * a ^ na;",
            "            b = 2 * b ^ nb;",
            "            ll neg_a = a ^ 1;",
            "            ll neg_b = b ^ 1;",
            "",
            "            adj[neg_a].push_back(b);",
            "            adj[neg_b].push_back(a);",
            "",
            "            radj[a].push_back(neg_b);",
            "            radj[b].push_back(neg_a);",
            "        }",
            "};",
        },
    }),

    s("kosaraju", {
        t {
            "class Kosaraju {",
            "public:",
            "    vll low;",
            "    ll N;",
            "    vll stack;",
            "    umap<ll, vll> adj;",
            "    umap<ll, vll> radj;",
            "    vector<bool> visited;",
            "",
            "public:",
            "    Kosaraju(umap<ll, vll> adj, umap<ll, vll> radj, ll n)",
            "        : adj(adj),",
            "          radj(radj),",
            "          N(n) {",
            "        low.assign(N, -1);",
            "        visited.assign(n, false);",
            "        kosaraju();",
            "    }",
            "",
            "    void dfs1(ll curr) {",
            "        visited[curr] = true;",
            "        for (ll& x : adj[curr]) {",
            "            if (!visited[x]) dfs1(x);",
            "        }",
            "        stack.push_back(curr);",
            "    }",
            "",
            "    void dfs2(ll curr, ll id) {",
            "        visited[curr] = true;",
            "        low[curr] = id;",
            "        for (ll& x : radj[curr]) {",
            "            if (!visited[x]) dfs2(x, id);",
            "        }",
            "    }",
            "",
            "    void kosaraju() {",
            "        for (int i = 0; i < N; i++) {",
            "            if (!visited[i]) dfs1(i);",
            "        }",
            "",
            "        visited.assign(visited.size(), false);",
            "",
            "        while (!stack.empty()) {",
            "            ll top = stack.back();",
            "            stack.pop_back();",
            "            if (!visited[top]) dfs2(top, top);",
            "        }",
            "    }",
            "};",
        },
    }),

    s("fac_inv_fac", {
        t {
            "const int N = 1e5 + 10;",
            "const long long MOD = 1e9 + 7;",
            "vector<long long> fac(N, 1);",
            "vector<long long> inv_fac(N, 1);",
            "",
            "// Precompute factorials modulo MOD",
            "for (int i = 1; i < N; i++) {",
            "    fac[i] = fac[i - 1] * i % MOD;",
            "}",
            "",
            "// Precompute inverse factorials using Fermat's little theorem",
            "inv_fac[N - 1] = 1;",
            "long long power = 1;",
            "// Modular inverse of fac[N-1]",
            "long long a = fac[N - 1];",
            "long long b = MOD - 2;",
            "long long res = 1;",
            "while (b) {",
            "    if (b & 1) res = res * a % MOD;",
            "    a = a * a % MOD;",
            "    b >>= 1;",
            "}",
            "inv_fac[N - 1] = res;",
            "",
            "// Compute remaining inverse factorials",
            "for (int i = N - 2; i >= 0; i--) {",
            "    inv_fac[i] = inv_fac[i + 1] * (i + 1) % MOD;",
            "}",
        },
    }),

    s("tarjan", {
        t {
            "class Tarjan {",
            "public:",
            "    vll low, ids;",
            "    vector<bool> on_stack;",
            "    ll N;",
            "    vll stack;",
            "    ll id = 0;",
            "    umap<ll, vll> adj;",
            "",
            "public:",
            "    Tarjan(umap<ll, vll> adj, ll n)",
            "        : adj(adj),",
            "          N(n) {",
            "        on_stack.assign(N, false);",
            "        low.assign(N, LLONG_MAX);",
            "        ids.assign(N, -1);",
            "",
            "        tarjan();",
            "    }",
            "",
            "    void dfs(ll curr) {",
            "        on_stack[curr] = true;",
            "        stack.push_back(curr);",
            "        ids[curr] = id;",
            "        low[curr] = id;",
            "        id++;",
            "        for (ll& nei : adj[curr]) {",
            "            if (ids[nei] == -1) dfs(nei);",
            "            if (on_stack[nei]) low[curr] = min(low[curr], low[nei]);",
            "        }",
            "",
            "        if (ids[curr] == low[curr]) {",
            "            while (true) {",
            "                ll top = stack.back();",
            "                stack.pop_back();",
            "                on_stack[top] = false;",
            "                low[top] = low[curr];",
            "                if (top == curr) break;",
            "            }",
            "        }",
            "    }",
            "",
            "    void tarjan() {",
            "        for (int i = 0; i < N; i++) {",
            "            if (ids[i] == -1) dfs(i);",
            "        }",
            "    }",
            "};",
        },
    }),

    s("floyd", {
        t {

            "for (int k = 0; k < n; k++) {",
            "	   for (int i = 0; i < n; i++) {",
            "        for (int j = 0; j < n; j++) {",
            "           if (dist[i][k] != LLONG_MAX && dist[k][j] != LLONG_MAX) {",
            "                dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]);",
            "            }",
            "        }",
            "    }",
            "}",
        },
    }),

    s("dijkstra", {
        t {
            "auto dijkstra = [&](ll src, ll dest, umap<ll, vector<pair<ll,ll>>> &adj) {",
            "    umap<ll, ll> par;",
            "    priority_queue<pair<ll, ll>, vector<pair<ll, ll>>, greater<pair<ll, ll>>> heap;",
            "    vll dist(dest + 1, LLONG_MAX);",
            "",
            "    dist[src] = 0;",
            "    par[src] = src;",
            "    heap.push({0, src});",
            "",
            "    while (!heap.empty()) {",
            "        auto [cw, cc] = heap.top();",
            "        heap.pop();",
            "        if (cw > dist[cc]) continue;",
            "",
            "        for (auto &[nei, wei] : adj[cc]) {",
            "            if (cw + wei < dist[nei]) {",
            "                dist[nei] = cw + wei;",
            "                par[nei] = cc;",
            "                heap.push({dist[nei], nei});",
            "            }",
            "        }",
            "    }",
            "",
            "    if (!par.count(dest)) return vll{ -1 };",
            "",
            "    vll path;",
            "    ll curr = dest;",
            "    while (curr != par[curr]) {",
            "        path.push_back(curr);",
            "        curr = par[curr];",
            "    }",
            "    path.push_back(src);",
            "    reverse(path.begin(), path.end());",
            "",
            "    return path;",
            "};",
        },
    }),

    s("seg_lazy", {
        t {
            "class Segment {",
            "    private:",
            "        vll tree, lazy;",
            "        vll nums;",
            "        ll n;",
            "",
            "        void build(ll pos, ll l, ll r) {",
            "            if (l == r) {",
            "                tree[pos] = nums[l];",
            "                return;",
            "            }",
            "            ll mid = l + (r - l) / 2;",
            "            build(left(pos), l, mid);",
            "            build(right(pos), mid + 1, r);",
            "            tree[pos] = tree[left(pos)] + tree[right(pos)];",
            "        }",
            "",
            "        void updateHelper(ll pos, ll l, ll r, ll val, ll L, ll R) {",
            "            push(pos, l, r);",
            "            if (l > R || r < L) return;",
            "            if (l >= L && r <= R) {",
            "                lazy[pos] += val;",
            "                push(pos, l, r);",
            "                return;",
            "            }",
            "            ll mid = l + (r - l) / 2;",
            "            updateHelper(left(pos), l, mid, val, L, R);",
            "            updateHelper(right(pos), mid + 1, r, val, L, R);",
            "            tree[pos] = tree[left(pos)] + tree[right(pos)];",
            "        }",
            "",
            "        ll queryHelper(ll pos, ll l, ll r, ll L, ll R) {",
            "            push(pos, l, r);",
            "            if (l > R || r < L) return -1;",
            "            if (l >= L && r <= R) return tree[pos];",
            "            ll mid = l + (r - l) / 2;",
            "            ll x = queryHelper(left(pos), l, mid, L, R);",
            "            ll y = queryHelper(right(pos), mid + 1, r, L, R);",
            "            if (x != -1) return x;",
            "            return y;",
            "        }",
            "",
            "    public:",
            "        Segment(vll nums) {",
            "            this->nums = nums;",
            "            n = nums.size();",
            "            tree.assign(4 * n, 0);",
            "            lazy.assign(4 * n, 0);",
            "            build(0, 0, n - 1);",
            "        }",
            "",
            "        ll left(ll pos) { return (pos << 1) + 1; }",
            "        ll right(ll pos) { return (pos << 1) + 2; }",
            "",
            "        void update(ll l, ll r, ll val) {",
            "            updateHelper(0, 0, n - 1, val, l, r);",
            "        }",
            "",
            "        ll query(ll idx) { return queryHelper(0, 0, n - 1, idx, idx); }",
            "",
            "        void push(ll pos, ll l, ll r) {",
            "            if (lazy[pos] != 0) {",
            "                tree[pos] += lazy[pos] * (r - l + 1);",
            "                if (l < r) {",
            "                    lazy[left(pos)] += lazy[pos];",
            "                    lazy[right(pos)] += lazy[pos];",
            "                }",
            "                lazy[pos] = 0;",
            "            }",
            "        }",
            "};",
        },
    }),

    s("seg_rmq", {
        t {
            "typedef long long ll;",
            "typedef vector<ll> vl;",
            "",
            "struct Node {",
            "    ll val;",
            "    Node(ll v = LLONG_MAX) : val(v) {}",
            "};",
            "",
            "class SegmentTree {",
            "    int n;",
            "    vector<Node> tree;",
            "    vl nums;",
            "",
            "    int left(int p) { return (p << 1) + 1; }",
            "    int right(int p) { return (p << 1) + 2; }",
            "",
            "    void build(int p, int l, int r) {",
            "        if (l == r) {",
            "            tree[p] = Node(nums[l]);",
            "            return;",
            "        }",
            "        int mid = l + (r - l) / 2;",
            "        build(left(p), l, mid);",
            "        build(right(p), mid + 1, r);",
            "        tree[p].val = min(tree[left(p)].val, tree[right(p)].val);",
            "    }",
            "",
            "    ll queryRange(int p, int l, int r, int L, int R) {",
            "        if (l > R || r < L) return LLONG_MAX;",
            "        if (L <= l && r <= R) return tree[p].val;",
            "        int mid = l + (r - l) / 2;",
            "        return min(queryRange(left(p), l, mid, L, R),",
            "                   queryRange(right(p), mid + 1, r, L, R));",
            "    }",
            "",
            "    void updatePoint(int p, int l, int r, int idx, ll val) {",
            "        if (l == r) {",
            "            tree[p] = Node(val);",
            "            return;",
            "        }",
            "        int mid = l + (r - l) / 2;",
            "        if (idx <= mid)",
            "            updatePoint(left(p), l, mid, idx, val);",
            "        else",
            "            updatePoint(right(p), mid + 1, r, idx, val);",
            "        tree[p].val = min(tree[left(p)].val, tree[right(p)].val);",
            "    }",
            "",
            "public:",
            "    SegmentTree(const vl& a) : nums(a) {",
            "        n = nums.size();",
            "        tree.assign(4 * n, Node());",
            "        build(0, 0, n - 1);",
            "    }",
            "",
            "    ll queryRange(int L, int R) { return queryRange(0, 0, n - 1, L, R); }",
            "    void updatePoint(int idx, ll val) { updatePoint(0, 0, n - 1, idx, val); }",
            "};",
        },
    }),

    s("seg_mod", {
        t {
            "typedef vector<ll> vl;",
            "",
            "struct Node {",
            "    ll sum;",
            "    ll maxVal;",
            "    Node(ll s = 0, ll m = LLONG_MIN) : sum(s), maxVal(m) {}",
            "};",
            "",
            "class SegmentTree {",
            "    int n;",
            "    vector<Node> tree;",
            "    vl nums;",
            "",
            "    int left(int p) { return (p << 1) + 1; }",
            "    int right(int p) { return (p << 1) + 2; }",
            "",
            "    void build(int p, int l, int r) {",
            "        if (l == r) {",
            "            tree[p] = Node(nums[l], nums[l]);",
            "            return;",
            "        }",
            "        int mid = l + (r - l) / 2;",
            "        build(left(p), l, mid);",
            "        build(right(p), mid + 1, r);",
            "        pull(p);",
            "    }",
            "",
            "    void pull(int p) {",
            "        tree[p].sum = tree[left(p)].sum + tree[right(p)].sum;",
            "        tree[p].maxVal = max(tree[left(p)].maxVal, tree[right(p)].maxVal);",
            "    }",
            "",
            "    ll querySum(int p, int l, int r, int L, int R) {",
            "        if (l > R || r < L) return 0;",
            "        if (L <= l && r <= R) return tree[p].sum;",
            "        int mid = l + (r - l) / 2;",
            "        return querySum(left(p), l, mid, L, R) +",
            "               querySum(right(p), mid + 1, r, L, R);",
            "    }",
            "",
            "    void updatePoint(int p, int l, int r, int idx, ll val) {",
            "        if (l == r) {",
            "            tree[p] = Node(val, val);",
            "            return;",
            "        }",
            "        int mid = l + (r - l) / 2;",
            "        if (idx <= mid) updatePoint(left(p), l, mid, idx, val);",
            "        else updatePoint(right(p), mid + 1, r, idx, val);",
            "        pull(p);",
            "    }",
            "",
            "    void modRange(int p, int l, int r, int L, int R, ll modder) {",
            "        if (l > R || r < L || tree[p].maxVal < modder) return;",
            "        if (l == r) {",
            "            tree[p].sum %= modder;",
            "            tree[p].maxVal = tree[p].sum;",
            "            return;",
            "        }",
            "        int mid = l + (r - l) / 2;",
            "        modRange(left(p), l, mid, L, R, modder);",
            "        modRange(right(p), mid + 1, r, L, R, modder);",
            "        pull(p);",
            "    }",
            "",
            "public:",
            "    SegmentTree(const vl &a) : nums(a) {",
            "        n = nums.size();",
            "        tree.assign(4 * n, Node());",
            "        build(0, 0, n - 1);",
            "    }",
            "",
            "    ll querySum(int L, int R) { return querySum(0, 0, n - 1, L, R); }",
            "    void updatePoint(int idx, ll val) { updatePoint(0, 0, n - 1, idx, val); }",
            "    void modRange(int L, int R, ll modder) { modRange(0, 0, n - 1, L, R, modder); }",
            "};",
        },
    }),
    s("fast", {
        t {
            "#include <bits/stdc++.h>",
            "using namespace std;",
            "",
            "#define loop_from(i, s, n) for (int i = s; i < n; i++)",
            "#define loop(i, n) for (int i = 0; i < n; i++)",
            "#define MOD 1'000'000'007",
            "#define pb push_back()",
            "#define pob pop_back()",
            "#define int long long",
            "#define nl '\\n'",
            "#define print(x) cout << (x) << endl",
            "#define show(v)                         \\",
            '    for (auto& x : v) cout << x << " "; \\',
            "    cout << endl",
            '#define debug(i) cout << #i << ": " << i << endl',
            "",
            "#define infi numeric_limits<ll>::max()",
            "#define ninfi numeric_limits<ll>::min()",
            "#define infd numeric_limits<ld>::infinity()",
            "#define ninfd -numeric_limits<ld>::infinity()",

            "#define all(x) (x).begin(), (x).end()",
            "",
            "typedef long long ll;",
            "typedef long double ld;",
            "typedef vector<ll> vll;",
            "",
            "template <typename K, typename V>",
            "using umap = unordered_map<K, V>;",
            "",

            "static mt19937 rng(chrono::steady_clock::now().time_since_epoch().count());",
            "#define RAND(a, b) uniform_int_distribution<long long>(a, b)(rng)",

            "ll big = RAND(1, 1e9);",

            "long long modPow(long long base, long long exp, long long mod) {",
            "    long long res = 1;",
            "    base %= mod;",
            "",
            "    while (exp > 0) {",
            "        if (exp % 2 == 1) {",
            "            res = (res * base) % mod;",
            "        }",
            "",
            "        base = (base * base) % mod;",
            "        exp /= 2;",
            "    }",
            "",
            "    return res;",
            "}",
            "",
            "",

            "void solve() {",
            "\t",
        },
        i(0),
        t {
            "",
            "}",
            "",
            "int32_t main() {",
            "    ios::sync_with_stdio(false);",
            "    cin.tie(nullptr);",
            "",
            "    int t = 1;",
            "\t",
        },
        i(1),
        t {
            "",
            "    loop_from(_, 0, t) { solve(); }",
            "}",
        },
    }),

    s("tcase", {
        t {
            "int t;",
            "cin >> t;",
            "while (t--) {",
            "    ",
        },
        i(1),
        t { "", "}" },
    }),

    s("rint", {
        t "int ",
        i(1, "num"),
        t { ";", "cin >> " },
        rep(1),
        t { ";", "" }, -- Ends the line after the snippet content
        i(0), -- Final node: moves cursor to a new line ready for further editing
    }),

    s("rstr", {
        t "string ",
        i(1, "word"),
        t { ";", "cin >> " },
        rep(1),
        t { ";", "" },
        i(0),
    }),

    s("riarr", {
        t "vector<ll> ",
        i(1, "arr"),
        t "(",
        i(2, "n"),
        t ")",
        t { ";", "for (ll &x : " },
        rep(1),
        t { "){", "\tcin >> x;", "}" },
        i(0),
    }),

    s("rsarr", {
        t "vector<string> ",
        i(1, "arr"),
        t "(",
        i(2, "n"),
        t ")",
        t { ";", "for (string &s : " },
        rep(1),
        t { "){", "\tcin >> s;", "}" },
        i(0),
    }),

    s("rcstr", {
        t "vector<char> ",
        i(1, "arr"),
        t { ";", "string s;", "cin >> s;", "" },
        -- t({ "" }),
        rep(1),
        t ".assign(s.begin(), s.end());",
        i(0),
    }),

    s("rcsmat", {
        t "vector<vector<char>> ",
        i(1, "mat"),
        t { "(r, vector<char>(c));", "" },
        t { "for (int i = 0; i < r; i++) {", "\tstring s;", "\tcin >> s;", "\t" },
        rep(1),
        t { "[i].assign(s.begin(), s.end());", "}" },
        i(0),
    }),

    s("rsmat", {
        t "vector<vector<string>> ",
        i(1, "mat"),
        t { "(r, vector<string>(c));", "" },
        t { "for (int i = 0; i < r; i++)", "\tfor (int j = 0; j < c; j++) {", "\t\tcin >> " },
        rep(1),
        t { "[i][j];", "\t}" },
        i(0),
    }),

    s("rimat", {
        t "vector<vector<int>> ",
        i(1, "mat"),
        t { "(r, vector<int>(c));", "" },
        t { "for (int i = 0; i < r; i++)", "\tfor (int j = 0; j < c; j++) {", "\t\tcin >> " },
        rep(1),
        t { "[i][j];", "\t}" },
        i(0),
    }),

    s("grid_pre_sum", {
        t {
            "// 2D Prefix Sum for grid",
            "vector<vector<ll>> pre(n + 1, vector<ll>(n + 1));",
            "for (ll r = 0; r < n; ++r) {",
            "    for (ll c = 0; c < n; ++c) {",
            "        pre[r + 1][c + 1] = (grid[r][c] == '*') + pre[r][c + 1] + pre[r + 1][c] - pre[r][c];",
            "    }",
            "}",
        },
    }),
    s("grid_pre_sum_calc", {
        t {
            "// Query sum in rectangle (r1, c1) to (r2, c2), 0-based indices",
            "ll ans = pre[r2 + 1][c2 + 1] + pre[r1][c1] - pre[r2 + 1][c1] - pre[r1][c2 + 1];",
        },
    }),
})
