local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local rep = require("luasnip.extras").rep

vim.api.nvim_set_keymap("i", "<A-.>", [[<cmd>lua require'luasnip'.jump(1)<CR>]], { noremap = true })
vim.api.nvim_set_keymap("s", "<A-.>", [[<cmd>lua require'luasnip'.jump(1)<CR>]], { noremap = true })

vim.api.nvim_set_keymap("i", "<A-,>", [[<cmd>lua require'luasnip'.jump(-1)<CR>]], { noremap = true })
vim.api.nvim_set_keymap("s", "<A-,>", [[<cmd>lua require'luasnip'.jump(-1)<CR>]], { noremap = true })

ls.add_snippets("python", {

    s("kmp", {
        t {
            "# ---------- KMP String Matching ----------",
            "def kmp(haystack, needle):",
			"    if needle == '':",
			"        return 0",
            "    prev, i = 0, 1",
            "    n, m = len(haystack), len(needle)",
            "",
            "    lps = [0] * m",
            "",
            "    while i < m:",
            "        if needle[i] == needle[prev]:",
            "            lps[i] = prev + 1",
            "            prev, i = prev + 1, i + 1",
            "        elif prev == 0:",
            "            lps[i], i = 0, i + 1",
            "        else:",
            "            prev = lps[prev - 1]",
            "",
            "    i, j = 0, 0",
            "    while i < n:",
            "        if haystack[i] == needle[j]:",
            "            i, j = i + 1, j + 1",
            "        elif j == 0:",
            "            i += 1",
            "        else:",
            "            j = lps[j - 1]",
            "",
            "        if j == m:",
            "            return i - m",
            "",
            "    return -1",
        },
        i(0),
    }),

    s("tarjan_bridges", {
        t {
            "# ---------- Tarjan's Algorithm for Bridges ----------",
            "tin = {}",
            "low = {}",
            "timer = [0]",
            "visited = set()",
            "",
            "critical = []",
            "def dfs(curr, prev):",
            "    tin[curr] = low[curr] = timer[0]",
            "    timer[0] += 1",
            "    visited.add(curr)",
            "",
            "    for nei in adj[curr]:",
            "        if nei == prev:",
            "            continue",
            "        if nei in visited:",
            "            low[curr] = min(low[nei], low[curr])",
            "        else:",
            "            dfs(nei, curr)",
            "            low[curr] = min(low[nei], low[curr])",
            "            if low[nei] > tin[curr]:",
            "                critical.append([nei, curr])",
            "",
            "for i in range(n):",
            "    if i not in visited:",
            "        dfs(i, -1)",
            "",
            "return critical",
        },
        i(0),
    }),

    s("union_find", {
        t {
            "# ---------- Union-Find / Disjoint Set Union ----------",
            "class UnionFind:",
            "    def __init__(self, n):",
            "        self.par = list(range(n))",
            "        self.rank = [0] * n",
            "",
            "    def find(self, node):",
            "        if self.par[node] != node:",
            "            self.par[node] = self.find(self.par[node])  # Path compression",
            "        return self.par[node]",
            "",
            "    def union(self, x, y):",
            "        rx, ry = self.find(x), self.find(y)",
            "        if rx == ry:",
            "            return False  # Already connected",
            "        if self.rank[rx] < self.rank[ry]:",
            "            self.par[rx] = ry",
            "        elif self.rank[rx] > self.rank[ry]:",
            "            self.par[ry] = rx",
            "        else:",
            "            self.par[rx] = ry",
            "            self.rank[ry] += 1",
            "        return True",
        },
        i(0),
    }),

    s("trie_lazy_deletion", {
        t {
            "# ---------- Trie Implementation (Lazy Deletion with Count) ----------",
            "class TrieNode:",
            "    def __init__(self):",
            "        self.children = [None] * 26",
            "        self.is_end = False",
            "        self.count = 0",
            "",
            "",
            "class Trie:",
            "    def __init__(self):",
            "        self.root = TrieNode()",
            "",
            "    def _char_to_index(self, ch):",
            "        return ord(ch) - ord('a')",
            "",
            "    def insert(self, word):",
            "        node = self.root",
            "        for ch in word:",
            "            idx = self._char_to_index(ch)",
            "            if not node.children[idx]:",
            "                node.children[idx] = TrieNode()",
            "            node = node.children[idx]",
            "            node.count += 1",
            "        node.is_end = True",
            "",
            "    def query(self, word):",
            "        node = self.root",
            "        for ch in word:",
            "            idx = self._char_to_index(ch)",
            "            child = node.children[idx]",
            "            if not child or child.count == 0:",
            "                return False",
            "            node = child",
            "        return node.is_end",
            "",
            "    def delete(self, word):",
            "        node = self.root",
            "        path = []",
            "",
            "        for ch in word:",
            "            idx = self._char_to_index(ch)",
            "            child = node.children[idx]",
            "            if not child or child.count == 0:",
            "                return  # word not found",
            "            path.append(child)",
            "            node = child",
            "",
            "        if not node.is_end:",
            "            return",
            "",
            "        node.is_end = False",
            "        for child in path:",
            "            child.count -= 1",
        },
        i(0),
    }),

    s("dijkstra", {
        t {
            "# ---------- Dijkstra Algorithm ----------",
            "def dijkstra(start, adj):",
            "    shortest = defaultdict(lambda: [float('inf'), ''])  # [distance, parent]",
            "    shortest[start][0] = 0",
            "",
            "    heap = [(0, start)]",
            "    processed = set()",
            "",
            "    while heap:",
            "        dist, curr = heappop(heap)",
            "        # if curr in processed:",
            "            # continue",
            "        # processed.add(curr)",
            "",
            "        for neighbor, weight in adj[curr].items():",
            "            new_dist = dist + weight",
            "            if new_dist < shortest[neighbor][0]:",
            "                shortest[neighbor] = [new_dist, curr]",
            "                heappush(heap, (new_dist, neighbor))",
            "",
            "    return shortest",
            "",
            "",
            "# ---------- Path Reconstruction ----------",
            "def get_path(shortest, end):",
            "    path = []",
            "    while end:",
            "        path.append(end)",
            "        end = shortest[end][1]",
            "    return path[::-1]",
        },
        i(0),
    }),

    s("sieve", {
        t {
            "_max = 10 ** 5 + 1",
            "prime = [True] * _max",
            "prime[0] = prime[1] = False",
            "",
            "for i in range(2, int(_max ** 0.5) + 1):",
            "    if prime[i]:",
            "        for j in range(i * i, _max, i):",
            "            prime[j] = False",
        },
        i(0),
    }),

    s("prime_factors", {
        t {
            "_max = 10 ** 5 + 1",
            "fac = [0] * _max",
            "for i in range(2, _max):",
            "    if fac[i] == 0:",
            "        for j in range(i, _max, i):",
            "            if fac[j] == 0:",
            "                fac[j] = i",
            "",
            "def factorize(x):",
            "    factors = set()",
            "    while x > 1:",
            "        factors.add(fac[x])",
            "        x //= fac[x]",
            "    return factors",
        },
        i(0),
    }),

    s("atleast", {
        t {
            "def atleast(nums, k, _max_len):",
            "    n = len(nums)",
            "    left = 0",
            "    seen = {}",
            "    ans = 0",
            "",
            "    for right, val in enumerate(nums):",
            "        seen[val] = seen.get(val, 0) + 1",
            "",
            "        while len(seen) >= k:",
            "            win_len = right - left + 1",
            "            if win_len <= _max_len:",
            "                ans += 1",
            "            seen[nums[left]] -= 1",
            "            if seen[nums[left]] == 0:",
            "                del seen[nums[left]]",
            "            left += 1",
            "",
            "    return ans",
        },
        i(0),
    }),

    s("atmost", {
        t {
            "def atmost(nums, K, max_len):",
            "    if K < 0:",
            "        return 0",
            "    left = 0",
            "    freq = {}",
            "    ans = 0",
            "    for right, val in enumerate(nums):",
            "        freq[val] = freq.get(val, 0) + 1",
            "        while len(freq) > K:",
            "            freq[nums[left]] -= 1",
            "            if freq[nums[left]] == 0:",
            "                del freq[nums[left]]",
            "            left += 1",
            "        # count valid subarrays ending at right",
            "        ans += min(right - left + 1, max_len)",
            "    return ans",
        },
        i(0),
    }),
    s("mergesort", {
        t {
            "class MergeSort:",
            "\tdef __init__(self, arr):",
            "\t\tself.arr = arr",
            "\t\tself.value = 0",
            "\t\tself.merge_sort(0, len(self.arr) - 1)",
            "\t\treturn self.value",
            "",
            "\tdef merge(self, left, right):",
            "\t\tmerged = []",
            "\t\ti = j = 0",
            "\t\twhile i < len(left) and j < len(right):",
            "\t\t\tif self.arr[left[i]] <= self.arr[right[j]]:",
            "\t\t\t\tmerged.append(left[i])",
            "\t\t\t\ti += 1",
            "\t\t\telse:",
            "\t\t\t\tmerged.append(right[j])",
            "\t\t\t\tj += 1",
            "\t\tmerged.extend(left[i:])",
            "\t\tmerged.extend(right[j:])",
            "\t\treturn merged",
            "",
            "\tdef merge_sort(self, l, r):",
            "\t\tif l > r:",
            "\t\t\treturn []",
            "\t\tif l == r:",
            "\t\t\treturn [self.arr[l]]",
            "\t\tmid = l + (r - l) // 2",
            "\t\tleft = self.merge_sort(l, mid)",
            "\t\tright = self.merge_sort(mid + 1, r)",
            "\t\treturn self.merge(left, right)",
        },
        i(0),
    }),

    s("segment", {
        t {
            "class SegmentTree:",
            "\tdef __init__(",
            "\t\tself,",
            "\t\tn,",
            "\t\tmerge,",
            "\t\tnums=[],",
            "\t\tidentity=0,",
            "\t):",
            "\t\tself.n = n",
            "\t\tself.merge = merge",
            "\t\tself.tree = [0] * (4 * n)",
            "\t\tself.identity = identity",
            "\t\tself.nums = nums",
            "\t\tif nums:",
            "\t\t\tself.build(0, 0, self.n - 1)",
            "",
            "\tdef build(self, curr, l, r):",
            "\t\tif l == r:",
            "\t\t\tself.tree[curr] = self.nums[l]",
            "\t\t\treturn",
            "\t\tmid = l + (r - l) // 2",
            "\t\tleft, right = self.lr(curr)",
            "\t\tself.build(left, l, mid)",
            "\t\tself.build(right, mid + 1, r)",
            "\t\tself.tree[curr] = self.merge(self.tree[left], self.tree[right])",
            "",
            "\tdef query(self, curr, l, r, ql, qr):",
            "\t\tif l > qr or r < ql:",
            "\t\t\treturn self.identity",
            "\t\tif ql <= l and r <= qr:",
            "\t\t\treturn self.tree[curr]",
            "\t\tmid = l + (r - l) // 2",
            "\t\tleft, right = self.lr(curr)",
            "\t\treturn self.merge(",
            "\t\t\tself.query(left, l, mid, ql, qr),",
            "\t\t\tself.query(right, mid + 1, r, ql, qr),",
            "\t\t)",
            "",
            "\tdef lr(self, i):",
            "\t\treturn (i * 2 + 1, i * 2 + 2)",
            "",
            "\tdef setUpdate(self, curr, l, r, pos, val):",
            "\t\t# take care of this setUpdate, change as you please",
            "\t\tself.nums[pos] = val",
            "\t\tself.update(curr, l, r, pos, val)",
            "",
            "\tdef update(self, curr, l, r, idx, val):",
            "\t\tif l == r:",
            "\t\t\t# take care of this update, change as you please",
            "\t\t\tself.tree[curr] = val",
            "\t\t\treturn",
            "\t\tmid = l + (r - l) // 2",
            "\t\tleft, right = self.lr(curr)",
            "\t\tif mid >= idx:",
            "\t\t\tself.update(left, l, mid, idx, val)",
            "\t\telse:",
            "\t\t\tself.update(right, mid + 1, r, idx, val)",
            "\t\tself.tree[curr] = self.merge(self.tree[left], self.tree[right])",
        },
        i(0),
    }),

    s("recur", {
        t {
            "import sys",
            "import threading",
            "from collections import Counter, defaultdict",
            "from bisect import bisect_left, bisect_right",
            "from copy import deepcopy",
            "import math",
            "",
            "# input = input",
            "input = sys.stdin.readline",
            "",
            "",
            "def solve():",
            "\t",
        },
        i(0),
        t {
            "",
            "",
            "",
            "def main():",
            "\tt = ",
        },
        i(1, "rint"),
        t {
            "",
            "\tfor _ in range(t):",
            "\t\tsolve()",
            "",
            "",
            "if __name__ == '__main__':",
            "\tsys.setrecursionlimit(1 << 30)",
            "\tthreading.stack_size(1 << 27)",
            "",
            "\tmain_thread = threading.Thread(target=main)",
            "\tmain_thread.start()",
            "\tmain_thread.join()",
        },
    }),

    s("smpre", {
        i(1, "fillhere"),
        t {
            " = deepcopy(",
        },
        i(2, "nums"),
        t {
            ")",
            "",
            "for nr in range(r):",
            "\tfor nc in range(1, c):",
            "\t\t",
        },
        rep(1),
        t {
            "[nr][nc] += ",
        },
        rep(1),
        t {
            "[nr][nc - 1]",
            "",
            "",
        },
    }),

    s("umpre", {
        i(1, "fillhere"),
        t " = deepcopy(",
        i(2, "nums"),
        t { ")", "" },
        t "for nc in range(c):",
        t { "", "\tfor nr in range(1, r):" },
        t { "\t\t" },
        rep(1),
        t "[nr][nc] += ",
        rep(1),
        t { "[nr - 1][nc]", "", "" },
    }),

    s("fmpre", {
        i(1, "pmat"),
        t " = deepcopy(",
        i(2, "nums"),
        t { ")", "" },
        t "for nr in range(r):",
        t { "", "\tfor nc in range(1, c):", "\t\t" },
        rep(1),
        t " [nr][nc] += ",
        rep(1),
        t "[nr][nc-1]",
        t { "", "for nc in range(c):", "\tfor nr in range(1, r):", "\t\t" },
        rep(1),
        t "[nr][nc] += ",
        rep(1),
        t { "[nr - 1][nc]", "", "" },
        t "",
        i(0),
    }),

    s("gridsum", {
        t {
            "(",
        },
        i(1, "pmat"),
        t { "    [row2][col2]" },
        t { "    - (" },
        rep(1),
        t { "[row1 - 1][col2] if row1 > 0 else 0)" },

        t { "    - (" },
        rep(1),
        t { "[row2][col1 - 1] if col1 > 0 else 0)" },

        t { "    + (" },
        rep(1),
        t { "[row1 - 1][col1 - 1] if row1 > 0 and col1 > 0 else 0)" },
        t { ")" },
    }),

    s("fast", {
        t {
            "import sys",
            "# sys.setrecursionlimit(10**6)",
            "from collections import *",
            "from bisect import bisect_left, bisect_right",
            "from copy import deepcopy",
            "from random import randint",
            "from math import *",
            "from heapq import *",
            "",
            "# input = input",
            "input = sys.stdin.readline",
            "",
            "",
            "def solve():",
            "\t",
        },
        i(0),
        t {
            "",
            "",
            "",
            "def main():",
            "\tt = ",
        },
        i(1, "rint"),
        t {
            "",
            "\tfor _ in range(t):",
            "\t\tsolve()",
            "",
            "",
            "if __name__ == '__main__':",
            "\tmain()",
        },
    }),

    s("rimat", {
        t {
            "[list(map(int, input().split())) for _ in range(r)]",
            "",
        },
    }),

    s("tcase", {
        t {
            "t = int(input())",
            "for _ in range(t):",
            "\t",
        },
        i(0),
    }),

    s("rint", {
        t {
            "int(input())",
            "",
        },
    }),

    s("rstr", {
        t {
            "input().strip()",
            "",
        },
    }),

    s("riarr", {
        t {
            "list(map(int, input().split()))",
            "",
        },
    }),

    s("rsarr", {
        t {
            "input().split()",
            "",
        },
    }),

    s("rcstr", {
        t {
            "list(x for x in input().strip())",
            "",
        },
    }),

    s("rcsmat", {
        t {
            "[[x for x in input().strip()] for _ in range(r)]",
            "",
        },
    }),

    s("rsmat", {
        t {
            "[list(input().split()) for _ in range(r)]",
            "",
        },
    }),

    s("rimat", {
        t {
            "[list(map(int,input().split())) for _ in range(r)]",
            "",
        },
    }),
})
